[project]
name = "downloads_organizer_railerival"
version = "0.1.2"
dependencies = [
    "pytest-mock>=3.15.1",
    "twine>=7.0.0",
]
requires-python = ">=3.14"
description = "Made to organize my downloads!! My first automation ;3"
authors = [{name = "Railerival", email = "lineupsvalorant8@gmail.com"}, ]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.md",]
#need to be added 
keywords = ["downloads","organizer","file_sorter"] 
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: End Users/Desktop",
  "Topic :: Desktop Environment :: File Managers",
  "Programming Language :: Python :: 3.14",
  "License :: OSI Approved :: MIT License"
]

[project.optional-dependencies]
tester = ["pytest>=9.1.1"]

[project.urls]
Repository = "https://github.com/Railerival/Downloads_organizer"
Issues = "https://github.com/Railerival/Downloads_organizer/issues"
Changelog = "https://github.com/Railerival/Downloads_organizer/blob/main/CHANGELOG.md"

#[project.scripts]
#run_program = "run_pgm.py"

#[project.entry-points]
#entry_point = "run_pgm.py"

[tool.setuptools.dynamic]
version.attr = "downloads_organizer.__version__"

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project.scripts]
organize = "pkgsample.add_cli:main"